/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_tsing_testdemo1_Demo1 */

#ifndef _Included_com_example_tsing_testdemo1_Demo1
#define _Included_com_example_tsing_testdemo1_Demo1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_tsing_testdemo1_Demo1
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_tsing_testdemo1_Demo1_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
