/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "com_example_tsing_testdemo1_Demo1.h"
/* Header for class com_example_tsing_testdemo1_Demo1 */


/*
 * Class:     com_example_tsing_testdemo1_Demo1
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_tsing_testdemo1_Demo1_sayHello
        (JNIEnv *env,jclass jclass){
    return (*env)->NewStringUTF(env,"JNi success");
}

